SELECT d.`ID` AS `ID`
     , MIN(d.`EMAIL`) AS `EMAIL`
     , MIN(d.`FIRST_NAME`) AS `FIRST_NAME`
     , MIN(d.`LAST_NAME`) AS `LAST_NAME`
FROM `DEVELOPERS` d
JOIN `SKILLCODES` s
WHERE s.`CATEGORY` = "Front End"
    AND CONV(d.`SKILL_CODE`, 10, 2) - CONV(s.`CODE`, 10, 2) NOT LIKE "%9%"
    AND CONV(d.`SKILL_CODE`, 10, 2) - CONV(s.`CODE`, 10, 2) NOT LIKE "%-%"
GROUP BY d.`ID`
ORDER BY d.`ID` ASC;